# yaml-language-server: $schema=../../schemas/status.schema.yaml
schema_version: "1.0"
analysis_type: pairwise
last_updated: "2026-01-30T00:00:00Z"

stages:
  comparisons:
    spec-kit_vs_bmad:
      status: completed
      last_updated: "2026-01-30T00:00:00Z"
    spec-kit_vs_openspec:
      status: completed
      last_updated: "2026-01-30T00:00:00Z"
    bmad_vs_openspec:
      status: completed
      last_updated: "2026-01-30T00:00:00Z"
  validation:
    last_run: "2026-01-30T10:00:00Z"
    status: passed
    errors: 0
    warnings: 0

overall_completion: 100
