# yaml-language-server: $schema=../../schemas/status.schema.yaml
schema_version: "1.0"
analysis_type: pairwise
last_updated: "2026-01-30T00:00:00Z"

stages:
  comparisons:
    spec-kit_vs_bmad:
      status: pending
    spec-kit_vs_openspec:
      status: pending
    bmad_vs_openspec:
      status: pending
  validation:
    last_run: null
    status: not-started
    errors: 0
    warnings: 0

overall_completion: 0
