# yaml-language-server: $schema=../../schemas/status.schema.yaml
schema_version: "1.0"
framework: spec-kit
last_updated: "2026-01-30T00:00:00Z"

stages:
  documents:
    key_sources:
      status: completed
      last_updated: "2026-01-30T00:00:00Z"
    reading_notes:
      status: completed
      last_updated: "2026-01-30T00:00:00Z"
  glossaries:
    glossary:
      status: completed
      last_updated: "2026-01-30T00:00:00Z"
      item_count: 25
    artifact_taxonomy:
      status: completed
      last_updated: "2026-01-30T00:00:00Z"
      item_count: 10
    concept_mapping:
      status: completed
      last_updated: "2026-01-30T00:00:00Z"
      item_count: 15
  descriptions:
    philosophy:
      status: completed
      last_updated: "2026-01-30T00:00:00Z"
    workflow:
      status: completed
      last_updated: "2026-01-30T00:00:00Z"
    context_organization:
      status: completed
      last_updated: "2026-01-30T00:00:00Z"
    specific_features:
      status: completed
      last_updated: "2026-01-30T00:00:00Z"
  summary:
    executive_summary:
      status: completed
      last_updated: "2026-01-30T00:00:00Z"
    conclusions:
      status: completed
      last_updated: "2026-01-30T00:00:00Z"
  validation:
    last_run: null
    status: not-started
    errors: 0
    warnings: 0

overall_completion: 100
ready_for_cross_analysis: true
